### ISSUE TITLE
Town NPCs Lose Invincibility Frames

### ISSUE THREAD

**Issue by PacoDaPea** [morpeed/SimpleNPCStats2#1]
Town NPCs seem to lose their invincibility frames when included in the customizer config even if they only have default values, making it easier for them to die.
Problem persists even when I only have this mod and Cheat Sheet enabled.
Shouldn't be too hard to replicate. Just make a small box, spawn an affected and unaffected town NPC, and then spawn a zombie or skeleton.

**Comment by morpeed** [comment]
Okay I can see why, it's with any NPC damaging other NPC with contact damage (such as queen bee)
Immunity frames were broken with AI Speed but this is a side effect of my fix for that, I'll look into it, I'll push a temporary fix for this now
